### ISSUE TITLE
scoscdir program fails to start on boot

### ISSUE THREAD

**Issue by bburdette** [chronopoulos/cyclophone#2]
I'd like the ~/code/cycophone/startup/bananapi_startall.sh script to run on boot, but when I do that the scoscdir program has some kind of problem and doesn't start.  All the other programs do ok.  Is there some way to leave the failed program up in screen so I can look at its error messages?

**Comment by chronopoulos** [comment]
i would just pipe its stdout and stderr to a log file that you can check
post-mortem

**Comment by bburdette** [comment]
I'll give it a shot.  I guess you're getting all these issues to your inbox huh?  I'm trying to make a list of things to work on in anticipation of a cyclophone hack day.

**Comment by chronopoulos** [comment]
yea, no problem, i can turn off notifications if they get annoying.
cyclophone hack day! very cool - just you or other people hacking on it too?

**Comment by bburdette** [comment]
ok set it up to pipe output into files, but the files come up empty.  Hmmm!

Sent you an email with pix of the audio amp before I took it back out for maker faire.

**Comment by chronopoulos** [comment]
Show me the bash command?

**Comment by bburdette** [comment]
under cyclophone/startup its bananapi_startscoscdir.sh.  It gets kicked off by bananapi_startall.sh, which in turn is called from rc.local.  There's an example of the rc.local in the cyclophone/startup directory.  

Unfortunately I'm not at the cyclophone so I can't give you the exact syntax I used, but basically its something like this:

screen -d -m ~/.cabal/bin/scoscdir 192.168.8.174 8000 ~/cyclophone_samples/mmap.hs 192.168.8.174 8086 > ~/scoscdirout.txt 2> ~/scoscdirerr.txt

**Comment by chronopoulos** [comment]
ok, I just wanted to check that you were piping both stdout and stderr into
files. the syntax in your email looks good, but the line executed here in
the repo
https://github.com/chronopoulos/cyclophone/blob/master/startup/bananapi_startscoscdir.sh
doesn't
have those redirections. i guess you haven't pushed your most recent
changes?

_chris

**Comment by bburdette** [comment]
Yeah I was just doing that at the space last night, I just got blank files so I didn't push anything.  I'm sure its something dumb but I have no idea what.

**Comment by bburdette** [comment]
this is resolved as of a month or two ago.  At least on arch which is what the cyclophone uses now.  It uses systemd to start.
